### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [DerZyklop/dotfiles#5]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`fonts.sh`](https://github.com/DerZyklop/dotfiles/blob/599fcce70a836d1b24234b72c4cd2fe9893649fe/init/fonts.sh). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by DerZyklop** [comment]
Thank you. 
Fixed 91c6157a6e0ef1777d64869d9e9ee3539686c556
